In [2]:
import pandas as pd 

In [3]:
import numpy as np

In [4]:
from pandas import Series ,DataFrame

# Introduction to pandas Data Structures

### Series

In [4]:
obj = pd.Series([4,7,-5,3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2 = pd.Series([4,7,-5,3],index = ["d","b","a","c"])

In [12]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
obj2["a"]

-5

In [19]:
obj2["d"] = 6

In [20]:
obj2[["c","a","d"]]

c    3
a   -5
d    6
dtype: int64

In [21]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [22]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [26]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [27]:
"b" in obj2

True

In [28]:
"e" in obj2

False

In [29]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [31]:
obj3 = pd.Series(sdata)

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [34]:
obj4 = pd.Series(sdata,index =states)

In [35]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [38]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [40]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [41]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [42]:
obj3  #可实现自动对齐

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [43]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [44]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [45]:
obj4.name = "population"

In [46]:
obj4.index.name = "state"

In [47]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [48]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [49]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [50]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# DataFrame

In [51]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [53]:
frame = pd.DataFrame(data)

In [54]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [55]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [56]:
pd.DataFrame(data,columns = ["year","state","pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [61]:
frame2 = pd.DataFrame(data,columns = ["year","state","pop","debt"],
                     index = ['one', 'two', 'three', 'four',
                             'five', 'six'])

In [62]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [63]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [65]:
frame2["state"]

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [66]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [67]:
frame2.loc["three"]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [68]:
frame2["debt"] = 16.5

In [69]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [70]:
frame2["debt"] = np.arange(6.)

In [71]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [88]:
val = pd.Series([-1.2,-1.5,-1.7],index = ["two","four","five"])

In [73]:
frame2["debt"] = val

In [89]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [75]:
frame2["eastern"] = frame2.state =="ohio"

In [76]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN    False
two    2001    Ohio  1.7  -1.2    False
three  2002    Ohio  3.6   NaN    False
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [77]:
del frame2["eastern"]

In [79]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [80]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [81]:
frame3 = pd.DataFrame(pop)

In [125]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [83]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [94]:
pd.DataFrame(pop, index= pd.Series([2001, 2002, 2003]))

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [95]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [97]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [99]:
frame3.index.name = "year";frame3.columns.name = "state"

In [100]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [101]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [103]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Objects

In [104]:
obj = pd.Series(range(3),index = ["a","b","c"])

In [105]:
index = obj.index

In [106]:
index

Index(['a', 'b', 'c'], dtype='object')

In [107]:
index[1:]

Index(['b', 'c'], dtype='object')

In [108]:
index[1]

'b'

In [114]:
labels = pd.Index(np.arange(3))

In [110]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [111]:
obj2 = pd.Series([1.5,-2.5,0],index = labels)

In [112]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [123]:
obj2.index is index

False

In [126]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [128]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [130]:
"Ohio" in frame3.columns

True

In [131]:
2003 in frame3.index

False

In [133]:
dup_labels = pd.Index(["foo","foo","bar","bar"])

In [134]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

#  Essential Fuctionality

## Reindexing 

In [135]:
obj= pd.Series([4.5,7.2,-5.3,3.6],index = ["d","b","a","c"])

In [136]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [153]:
obj2 = obj.reindex(["a","b","c","d","e"])

In [154]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [140]:
obj3 = pd.Series(["blue","purple","yellow"],index = [0,2,4])

In [155]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [152]:
obj3.reindex(range(6),method = "ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [160]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ["a","d","c"],
                    columns=['Ohio', 'Texas', 'California'])

In [161]:
frame

Ohio  Texas  California
a     0      1           2
d     3      4           5
c     6      7           8

In [162]:
frame2 = frame.reindex(["a","b","c","d"])

In [163]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   6.0    7.0         8.0
d   3.0    4.0         5.0

In [165]:
states = ['Texas', 'Utah', 'California']

In [166]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
d      4   NaN           5
c      7   NaN           8

In [168]:
frame.loc[["a","b","c","d"],states]

D:\python\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    7.0   NaN         8.0
d    4.0   NaN         5.0

## Dropping Entries from an Axis
drop

In [169]:
obj = pd.Series (np.arange(5.),index=['a', 'b', 'c', 'd', 'e'])

In [170]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [172]:
new_obj = obj.drop("c")

In [173]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [174]:
obj.drop(["c","d"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [175]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [176]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [177]:
data.drop(["Colorado","Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [178]:
import pandas as pd 

In [179]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ["one","two","three","four"] )

In [180]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [181]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [182]:
data.drop("two",axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [183]:
data.drop(["two","four"],axis = 1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [184]:
data.drop(["two","four"],axis = "columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [185]:
obj= pd.Series(np.arange(5.),index = ["a","b","c","d","e"])

In [186]:
obj.drop("c",inplace = True)# return a new object

In [187]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [188]:
## Indexing Selecting and Filtering

In [193]:
obj= pd.Series(np.arange(4.),index = ["a","b","c","d",])

In [194]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [195]:
obj["b"]

1.0

In [196]:
obj[1]#series 可使用interge 或字符串进行选择

1.0

In [197]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [198]:
obj[["b","a","c"]]

b    1.0
a    0.0
c    2.0
dtype: float64

In [199]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [200]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [201]:
obj["b":"c"]

b    1.0
c    2.0
dtype: float64

In [202]:
obj["b":"c"] = 5  #series 的的切片选择包含结尾，一般python的切片不包含结尾

In [203]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [204]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ["one","two","three","four"] )

In [205]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [206]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [207]:
data[["three","one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [208]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [209]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [210]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [211]:
data[data < 5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [212]:
data[data < 5] = 0

In [213]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## Selection with loc and iloc

In [215]:
data.loc["Colorado",["two","three"]]

two      5
three    6
Name: Colorado, dtype: int32

In [216]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [217]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [218]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [219]:
data.loc[:"Utah","two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [220]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## Integer Indexes 

In [222]:
ser = pd.Series(np.arange(3.))

In [223]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [224]:
ser[-1]

KeyError: -1

In [225]:
ser2 = pd.Series(np.arange(3.),index = ["a","b","c"])

In [226]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [227]:
ser2[-1]

2.0

In [228]:
ser[:1]

0    0.0
dtype: float64

In [229]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [230]:
ser.iloc[:1]

0    0.0
dtype: float64

# Arithmetic and Data Alignment

In [231]:
s1 = pd.Series ([7.3,-2.5,3.4,1.5], index = ["a","c","d","e"])

In [232]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [233]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
              index = ["a","c","e","f","g"])

In [234]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [235]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [236]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns = list("bcd"),
                  index = ["Ohio","Texas","Colorado"])

In [237]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns = list("bde"),
                  index = ["Utah","Ohio","Texas","Oregon"])

In [238]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [239]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [240]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [241]:
df1 = pd.DataFrame({"A":[1,2]})

In [242]:
df2 = pd.DataFrame({"B":[3,4]})

In [243]:
df1-df2  #缺失会用NaN填补，NaN+1=NaN

A   B
0 NaN NaN
1 NaN NaN

In [244]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                   columns = list("abcd"))

In [245]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns = list("abcde"))

In [247]:
df2.loc[1,"b"]=np.nan

In [248]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [249]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [250]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [251]:
df1.add(df2,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [252]:
df1.reindex(columns = df2.columns,fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#  Operation between DataFrame and Series

In [253]:
arr = np.arange(12.).reshape((3,4))

In [254]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [255]:
arr[0]

array([0., 1., 2., 3.])

In [256]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [257]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns = list("bde"),
                    index = ["Utah","Ohio","Texas","Oregon"] )

In [258]:
series = frame.iloc[0]

In [259]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [260]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [261]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [262]:
series2 = pd.Series(range(3),index = ["b","e","f"])

In [263]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [264]:
series3 = frame["d"]

In [265]:
frame 

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [266]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [269]:
frame.sub(series3,axis = "index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Fuction Application and Mapping

In [271]:
frame = pd.DataFrame(np.random.randn(4,3),columns = list("bde"),
                     index = ["Utah","Ohio","Texas","Oregon"])

In [272]:
frame

b         d         e
Utah    1.621303  0.399405 -0.697606
Ohio   -1.883113  0.522535  1.209611
Texas  -0.364529  0.976738 -4.206451
Oregon -0.425200 -1.677580 -0.423103

In [273]:
np.abs(frame)

b         d         e
Utah    1.621303  0.399405  0.697606
Ohio    1.883113  0.522535  1.209611
Texas   0.364529  0.976738  4.206451
Oregon  0.425200  1.677580  0.423103

In [274]:
f = lambda x :x.max() - x.min()

In [276]:
frame.apply(f)

b    3.504415
d    2.654318
e    5.416062
dtype: float64

In [277]:
frame.apply(f,axis = "columns")

Utah      2.318908
Ohio      3.092724
Texas     5.183190
Oregon    1.254477
dtype: float64

In [278]:
def f(x):
    return pd.Series([x.min(),x.max()],index = ["min","max"])

In [279]:
frame.apply(f)

b         d         e
min -1.883113 -1.677580 -4.206451
max  1.621303  0.976738  1.209611

In [284]:
format = lambda x : "%.2f" % x

In [285]:
frame.applymap(format)

b      d      e
Utah     1.62   0.40  -0.70
Ohio    -1.88   0.52   1.21
Texas   -0.36   0.98  -4.21
Oregon  -0.43  -1.68  -0.42

In [286]:
frame["e"].map(format)

Utah      -0.70
Ohio       1.21
Texas     -4.21
Oregon    -0.42
Name: e, dtype: object

## Sorting and Ranking 

In [288]:
obj = pd.Series(range(4),index = ["d","a","b","c"])

In [289]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [290]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index = ["three","one"],
                    columns = ["d","a","b","c"])

In [291]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [292]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [293]:
frame.sort_index(axis = 1,ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

0  1  2
0  1  2  3
1  8  7  9

In [299]:
frame.sort_index()

0  1  2
0  1  2  3
1  8  7  9

In [300]:
obj = pd.Series ([4,7,-3,2])

In [302]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [303]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [304]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [305]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [309]:
frame.sort_index(axis = 1)

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [313]:
frame.sort_values(by="b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [308]:
frame.sort_values(by=["a","b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [314]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [315]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [316]:
obj.rank(method = "first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [317]:
obj.rank(ascending = False ,method = "max")

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [319]:
frame = pd.DataFrame({"b":[4.3,7,-3,2],"a":[0,1,0,1],
                     "c":[-2,5,8,-2.5]})

In [320]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [321]:
frame.rank(axis = "columns")

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

# Axis Indexes with Duplicate Labels
带有重复值的轴索引

In [322]:
obj = pd.Series(range(5),index = ["a","a","b","b","c"])

In [323]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [324]:
obj.index.is_unique

False

In [326]:
obj["a"]  #return series

a    0
a    1
dtype: int64

In [327]:
obj["c"]  # return scalar value

4

In [328]:
df = pd.DataFrame(np.random.randn(4,3),index = ["a","a","b","b"])

In [329]:
df

0         1         2
a  0.176774 -2.582147 -0.186577
a  1.413183  1.718099  0.265631
b -0.346209 -1.494867  0.829066
b -0.247289 -0.255139  0.019726

# Summarizing and Computing Descriptive Statistics

In [330]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
                 index = ["a","b","c","d"],columns = ["one","two"])

In [331]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [332]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [336]:
df.sum(axis = "columns")#or axis = 1 NA values are excluded unless the entire slice

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [337]:
df.mean(axis = "columns",skipna = False )

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [338]:
df.idxmax()

one    b
two    d
dtype: object

In [339]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [340]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [343]:
obj = pd.Series(["a","b","c","d"] * 4)

In [3]:
obj.describe()

NameError: name 'obj' is not defined

## Correlation and Covariance

In [57]:
import pandas_datareader.data as web

ModuleNotFoundError: No module named 'pandas_datareader'

NameError: name 'web' is not defined

ModuleNotFoundError: No module named 'pandas_datareader'

## Unique Values,Value Counts , and Membership

In [5]:
 obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [6]:
uniques = obj.unique()

In [7]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [10]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [11]:
pd.value_counts(obj.values,sort = False)

d    1
b    2
a    3
c    3
dtype: int64

In [12]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [13]:
mask = obj.isin(["b","c"])

In [14]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [15]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [16]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [17]:
unique_vals = pd.Series(["c","b","a"])

In [18]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

## 处理缺失值 

In [19]:
string_data = Series(["aardvark","artichoke",np.nan,"avocado"])

In [20]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [22]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [23]:
string_data[0] = None

In [24]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 滤除缺失值 

In [25]:
from numpy import nan as NA

In [26]:
data = Series([1,NA,3.5,NA,7])

In [27]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [28]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [33]:
data = pd.DataFrame([[1.,6.5,3.],[10,NA,NA],[NA,NA,NA],[NA,6.5,3.]])

In [34]:
data

0    1    2
0   1.0  6.5  3.0
1  10.0  NaN  NaN
2   NaN  NaN  NaN
3   NaN  6.5  3.0

In [35]:
cleaned = data.dropna()

In [37]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [38]:
data.dropna(how = "all")

0    1    2
0   1.0  6.5  3.0
1  10.0  NaN  NaN
3   NaN  6.5  3.0

In [39]:
data[4] = NA

In [40]:
data

0    1    2   4
0   1.0  6.5  3.0 NaN
1  10.0  NaN  NaN NaN
2   NaN  NaN  NaN NaN
3   NaN  6.5  3.0 NaN

In [43]:
data.dropna(axis = 1,how = "all")

0    1    2
0   1.0  6.5  3.0
1  10.0  NaN  NaN
2   NaN  NaN  NaN
3   NaN  6.5  3.0

### 填充缺失值 

In [51]:
df = DataFrame(np.random.randn(7,3))

In [54]:
df.iloc[:4,1] = NA;df.iloc[:2,2] = NA

In [55]:
df

0         1         2
0 -1.071938       NaN       NaN
1  0.643429       NaN       NaN
2 -1.299879       NaN       NaN
3 -0.700308       NaN  0.248186
4 -1.786331       NaN -0.968292
5 -0.139577 -0.957195  0.113121
6  0.676309 -0.932626 -1.444920

In [56]:
df.fillna(0)

0         1         2
0 -1.071938  0.000000  0.000000
1  0.643429  0.000000  0.000000
2 -1.299879  0.000000  0.000000
3 -0.700308  0.000000  0.248186
4 -1.786331  0.000000 -0.968292
5 -0.139577 -0.957195  0.113121
6  0.676309 -0.932626 -1.444920